/**
 * Simulates a Generative AI backend response.
 * In a real application, this would make a fetch() call to an LLM provider.
 */

function sleep(ms) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

export async function generateNotes(input) {
  // Simulate network delay based on input length to feel "realistic"
  const delay = Math.min(Math.max(input.length * 10, 1500), 4000);
  await sleep(delay);

  if (!input || input.trim().length < 5) {
      throw new Error("Please provide more context or a clearer topic to generate notes.");
  }

  const topic = input.slice(0, 50).replace(/\n/g, " ") + (input.length > 50 ? "..." : "");

  return `
# Study Notes: ${topic}

Here is a structured breakdown based on your input.

### Key Concepts

1. **Foundational Understanding**: The core principles dictate how this subject operates in real-world scenarios.
2. **Contextual Application**: Applying these rules requires understanding variable factors and edge cases.
3. **Critical Analysis**: Evaluating the outcomes helps iterate and improve upon the initial theory.

### Summary

The most important takeaway is that mastering these fundamentals provides a strong framework for advanced applications later on. Focus on practicing these core tenets before moving to complex edge cases.

---
*Generated by Gradify AI Simulator*
`;
}
